version: '3.8'

services:

  fastapi:
    build:
      context: api
    depends_on:
      - receiptdb
    ports:
      - 8000:80
    restart: always

  receiptdb:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: shopa
      POSTGRES_PASSWORD: etrusc1
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - 5432:5432
   

